const quotes = [
  "Get the best organic produce from Wendofresh – the taste of nature!",
  "Fresh, organic, and natural products delivered worldwide.",
  "Experience the difference with Wendofresh’s premium agricultural exports.",
  "Supporting sustainable farming practices for a better tomorrow.",
  "Bringing the world the freshest, chemical-free produce.",
  "Sustainably sourced, ethically grown – your organic produce destination.",
  "Farm-fresh produce, grown with care, ready for export.",
  "Wendofresh: Exporting premium organic products to the world.",
  "Taste the quality with Wendofresh’s organic agricultural exports.",
  "Freshness that travels – delivering top-notch produce worldwide.",
  "Your trusted partner in organic farming and export.",
  "High-quality organic products that you can trust.",
  "Committed to sustainability, committed to quality.",
  "Naturally grown and handpicked, ready to be enjoyed globally.",
  "Wendofresh: Where quality meets the earth’s best produce.",
  "Fruits, vegetables, and more – always organic, always fresh.",
  "Sustainably grown, globally enjoyed.",
  "From farm to table – organic products you can trust.",
  "Harvested with care, exported with pride.",
  "Leading the way in organic farming and global exports.",
  "Your premium source for the world’s freshest organic produce.",
  "We bring the world the best organic products from Kenya.",
  "Quality you can taste, freshness you can trust.",
  "Fresh organic produce, delivered worldwide with care.",
  "From nature to your doorstep – premium organic products.",
  "Growing with purpose, delivering with pride.",
  "Wendofresh – nourishing the world, one product at a time.",
  "Organic excellence from the heart of Kenya.",
  "Sustainability and quality – that’s Wendofresh.",
  "From our farms to your family – always fresh, always organic.",
  "Leading organic agricultural exports with a commitment to quality.",
  "Your source for organic and chemical-free produce.",
  "Organic farming at its best – from Wendofresh to you.",
  "Carefully grown, perfectly harvested, globally delivered.",
  "From local farms to international tables, with love and care.",
  "Pure, fresh, and organic – delivered to your door.",
  "The taste of nature, delivered worldwide.",
  "When freshness matters – trust Wendofresh for your organic needs.",
  "Organic products that are good for the earth and great for you.",
  "The freshest organic produce – from our farms to your table.",
  "Supporting farmers, supporting sustainability, supporting the earth.",
  "Handpicked with care, delivered with pride.",
  "Wendofresh: Bringing nature’s best to your table.",
  "Grown with love, harvested with care, delivered to you.",
  "Fresh, organic, and ready to go – that’s Wendofresh.",
  "Wendofresh: Your source for top-quality organic produce.",
  "From Kenyan farms to global markets, with quality you can trust.",
  "Nature’s best, grown organically, delivered globally.",
  "Organic farming with a commitment to sustainability and quality.",
  "Taste the freshness of nature with Wendofresh’s premium organic products.",
  "Grown with the earth’s best – delivered to your doorstep.",
  "Fresh, pure, and organic – that’s the Wendofresh promise.",
  "Your trusted partner for premium organic produce worldwide."
];

export default quotes;